### ISSUE TITLE
Embed schemaType

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#22]
Hi,

Is there any sample for using [Embed](https://v2.ottomanjs.com/classes/embedtype) type?

**Comment by AV25242** [comment]
Have asked the team will get back to you on this.This is something that lacks documentation

**Comment by AV25242** [comment]
Hope this will help 

```
const childSchema = new Schema({ name: String });
const parentSchema = new Schema({
  // Array of subdocuments
  children: [childSchema],
  // Single nested subdocument.
  child: childSchema
});
```

**Comment by bwgjoseph** [comment]
Thanks, it helps. I also have some more questions.

Is there any difference with the example you given, and this

```js
const childSchema = { name: String };
const parentSchema = new Schema({
  // Array of subdocuments
  children: [childSchema],
  // Single nested subdocument.
  child: childSchema
});
```

I tested, and both seem to be running fine but not sure if there's any underlying difference.

---

Also, if I declare using nested object, it will throw error.

```js
const childSchema = new ottoman.Schema({ name: String });
        const nestedChildSchema = new ottoman.Schema({
            type: {
                type: String,
                required: true,
                enum: ['Point'],
            },
            coordinates: {
                type: [Number],
                required: true,
            }
        })
        const parentSchema = new ottoman.Schema({
        // Array of subdocuments
        children: [childSchema],
        // Single nested subdocument.
        child: childSchema,
        nestedChild: nestedChildSchema,
        });

        const model = ottoman.model('Airplane', parentSchema);
        model.create({
            children: [
                {
                    name: 'a',
                },
                {
                    name: 'b'
                }
            ],
            child: {
                name: 'c'
            },
            nestedChild: {
                type: 'Point',
                coordinates: [1, 2, 3]
            }
        })

        const options = { consistency: SearchConsistency.LOCAL }

        const find = await model.find({}, options);
        console.log('ottoman', JSON.stringify(find.rows, null, 2));
```

And the error log

```js
Error: Property coordinates is a required type
      at Object.exports.buildFields (node_modules\ottoman\src\schema\helpers\fn-schema.ts:38:13)
      at new Schema (node_modules\ottoman\src\schema\schema.ts:71:19)
      at Z:\bwgjoseph\mongoose-vs-ottoman\test\ts\embed-schema.test.ts:50:35
      at step (test\ts\embed-schema.test.ts:52:23)
      at Object.next (test\ts\embed-schema.test.ts:33:53)
      at Z:\bwgjoseph\mongoose-vs-ottoman\test\ts\embed-schema.test.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (test\ts\embed-schema.test.ts:23:12)
      at Context.<anonymous> (test\ts\embed-schema.test.ts:48:18)
      at processImmediate (internal/timers.js:456:21)
```

Thanks

Actually, I think you just need to define as such, it will throw the error,

```js
const nestedChildSchema = new ottoman.Schema({
            type: {
                type: String,
                required: true,
                enum: ['Point'],
            },
            coordinates: {
                type: [Number],
                required: true,
            }
        })
```

**Comment by AV25242** [comment]
@bwgjoseph  the above ^^ seems to be a bug, our team is investigating. Good Catch !

**Comment by AV25242** [comment]
Issue created https://github.com/couchbaselabs/node-ottoman/issues/325

**Comment by bwgjoseph** [comment]
There's still some issue with embedded schema usage. Take a look at [embed-schema.test.ts](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/embed-schema.test.ts)

1. It doesn't work if embedded schema is not declared using `new ottoman.Schema` - see `ottoman - should create doc with embed nested schema 2`

```js
const childSchema = new ottoman.Schema({
	name: {
		type: String,
	}
});

// if new ottoman.Schema is not defined, then the data created will not be inserted
// const nestedChildSchema = new ottoman.Schema({
const nestedChildSchema = {
	type: {
		type: String,
		required: true,
		enum: ['Point'],
	},
	coordinates: {
		type: [Number],
		required: true,
	}
};
const parentSchema = new ottoman.Schema({
	// Array of subdocuments
	children: [childSchema],
	// Single nested subdocument.
	child: childSchema,
	nestedChild: nestedChildSchema,
});

const model = ottoman.model('Airplane', parentSchema);
const data = {
	children: [
		{
			name: 'a',
		},
		{
			name: 'b'
		}
	],
	child: {
		name: 'c'
	},
	nestedChild: {
		type: 'Point',
		coordinates: [1.23, 2.45, 3.56]
	}
};
await model.create(data);
```

The result would be

```js
{
    "_type": "Airplane",
    "child": {
      "name": "c"
    },
    "children": [
      {
        "name": "a"
      },
      {
        "name": "b"
      }
    ],
    "id": "f45edf40-1927-47c7-813d-ff02681b564a",
}
```

Based on previously understanding, declaring as `new ottoman.Schema` doesn't seem to affect `childSchema` but it seem to affect `nested (object) childSchema`

---

2. Throw error when using my actual test model - see `ottoman - should create doc with embed nested schema`

This could be some config / my own mistake but I don't see anything wrong with my code yet. 

So because of `1` above, I know that I need to declare `new ottoman.Schema` in order for it to work, so I went to update my `schema` to add in the `new ottoman.Schema` declaration but when I tried to run the test, it throws me...

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/0cbbc254a8d48dc21ed6d77e835780f542309f0a/test/ts/setup/model.ts#L41

```js
$ npm test

> mongoose-vs-ottoman@1.0.0 test Z:\bwgjoseph\mongoose-vs-ottoman
> mocha --require ts-node/register test/ts/*.ts --exit


TypeError: Invalid schema configuration: `undefined` is not a valid type at path `location`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mongoose\lib\schema.js:1010:11)
    at Schema.path (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mongoose\lib\schema.js:686:27)
    at Schema.add (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mongoose\lib\schema.js:496:12)
    at new Schema (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mongoose\lib\schema.js:127:10)
    at Object.<anonymous> (Z:\bwgjoseph\mongoose-vs-ottoman\test\ts\setup\model.ts:95:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (Z:\bwgjoseph\mongoose-vs-ottoman\test\ts\$and.test.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mocha\lib\esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mocha\lib\esm-utils.js:33:34)
    at Mocha.loadFilesAsync (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mocha\lib\mocha.js:431:19)
    at singleRun (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mocha\lib\cli\run-helpers.js:125:15)
    at exports.runMocha (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mocha\lib\cli\run-helpers.js:190:10)
    at Object.exports.handler (Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\mocha\lib\cli\run.js:362:11)
    at Z:\bwgjoseph\mongoose-vs-ottoman\node_modules\yargs\lib\command.js:241:49
npm ERR! Test failed.  See above for more details.
```

Maybe there's some hidden issue here, I don't see it yet. From what I see so far, it points back to the schema declaration in `model.ts` where after I added the `new ottoman.Schema`

**Comment by AV25242** [comment]
@bwgjoseph  our team is reviewing this, will get back to you

**Comment by AV25242** [comment]
Our team tried to reproduce number 2 and it seem to work without an error.

On 1 its an expected behavior

**Comment by bwgjoseph** [comment]
Any particular reason why it not declaring `new ottoman.Schema` work for non-nested object, but doesn't work for nested object (embedded)? As I also asked previously in https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/22#issuecomment-736593014 on the difference between declaring and not.

As for number 2, I will try to replicate it on my end, and see if I am able to.

**Comment by bwgjoseph** [comment]
I believe our last conversation, you mentioned that the team is checking on why is there a need to declare `Schema` on nested object but not required to do so in non-nested object right?

As for `2`, it was my mistake in declaring the schema, the behavior is consistent with the declaring vs not declaring `Schema` on nested object (schema)

**Comment by AV25242** [comment]
@bwgjoseph  thanks for the update, the delay on this is from my side as I was tasked to go through some documentation reference :). I have done that and now have asked more questions to the team. Sorry about the delay

**Comment by AV25242** [comment]
@bwgjoseph  its interesting. location is getting saved when our developer uses the code 

```
import {Schema, model, SearchConsistency, Ottoman, start} from 'ottoman'
const ottoman = new Ottoman();
ottoman.connect({
  connectionString: 'couchbase://localhost',
  password: 'password',
  username: 'Administrator',
  bucketName: 'travel-sample'
})
const childSchema = new Schema({
  name: {
    type: String,
  }
});
const nestedChildSchema = new Schema({
  type: {
    type: String,
    required: true,
    enum: ['Point'],
  },
  coordinates: {
    type: [Number],
    required: true,
  }
});
const parentSchema = new Schema({
  // Array of subdocuments
  children: [childSchema],
  // Single nested subdocument.
  child: childSchema,
  location: nestedChildSchema,
});
const begin = async () => {
  const Airplane = model('Airplane', parentSchema);
  await start()
  await Airplane.create( {
    children: [
      {
        name: 'a',
      },
      {
        name: 'b'
      }
    ],
    child: {
      name: 'c'
    },
    location: {
      type: 'Point',
      coordinates: [1.23, 2.45, 3.56]
    }
  });
  const options = { consistency: SearchConsistency.LOCAL }
  const find = await Airplane.find({}, options);
  console.log(find);
  console.log('ottoman', JSON.stringify(find.rows, null, 2));
}
begin()
```

**Comment by AV25242** [comment]
above is the code

**Comment by AV25242** [comment]
the only difference is his is against 7.0 and he is using alpha.12 (and works with alpha 13)
what is your server version ?

**Comment by josephstgh** [comment]
It's defined wrongly from what I'm testing

I'm testing with 

```js
// note no new schema
const nestedChildSchema = {
  type: {
    type: String,
    required: true,
    enum: ['Point'],
  },
  coordinates: {
    type: [Number],
    required: true,
  }
};
```

Running on alpha.12, 6.6

**Comment by AV25242** [comment]
ok so got the answer - its because nestedChildSchema has this special field / property `type` and the behavior  to recognize this special field is inside the Schema Class (same behavior as that of mongoose).

Also if you remove the special field `type` and just keep coordinates it should work regardless you newing it up or not.
hope this helps

**Comment by bwgjoseph** [comment]
Thanks for the explanation, will keep this open for a few more days
