### ISSUE TITLE
support for ssl/tls connection

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#44]
Hi,

If the Couchbase is setup with SSL/TLS enabled, how can we pass in the connection string, cert, etc to connect to Couchbase via `ottoman`?

This is critical to us, and we will be using it. Sorry that this wasn't brought up earlier

**Comment by AV25242** [comment]
Have created a ticket to investigate https://github.com/couchbaselabs/node-ottoman/issues/369

**Comment by AV25242** [comment]
@bwgjoseph  this feature was released with SDK 3.1.2, we hope to make this available with next release.

**Comment by AV25242** [comment]
Please check out alpha.22

**Comment by deskoh** [comment]
Got the following error when using `2.0.0-alpha.28` (similarly with `2.0.0-alpha.22`):

```txt
node_modules\couchbase\lib\connection.js:129
    this._inst = new binding.Connection(
                 ^

Error: LCB_ERR_INVALID_ARGUMENT (203): It is unambiguously determined that the error was caused because of invalid arguments from the user
    at new Connection (D:\code\ottoman-test\node_modules\couchbase\lib\connection.js:129:18)
    at Cluster._getConn (D:\code\ottoman-test\node_modules\couchbase\lib\cluster.js:610:14)
    at new Bucket (D:\code\ottoman-test\node_modules\couchbase\lib\bucket.js:20:26)     
    at Cluster.bucket (D:\code\ottoman-test\node_modules\couchbase\lib\cluster.js:482:12)
    at Ottoman.connect (D:\code\ottoman-test\node_modules\ottoman\lib\ottoman\ottoman.js:134:41)
    at Object.<anonymous> (D:\code\ottoman-test\index.js:16:28)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 203
}
```

Code used:

```js
const { Ottoman } = require('ottoman');
const ottoman = new Ottoman();
const connection = ottoman.connect({
  connectionString: 'couchbase://localhost',
  bucketName: 'travel-sample',
  username: 'admin',
  password: 'password',
  trustStorePath: 'D:/servercertfiles/ca.pem'
})
```

Same error if I change the `trustStorePath` to   relative path such as `./servercertfiles/ca.pem`, or even some random string like `xxx`.

No errors if I remove `trustStorePath` option.

**Comment by deskoh** [comment]
Turns out I have to use `couchbases://localhost` with an `s`.

Got a hint from [here](https://github.com/couchbase/libcouchbase/blob/master/doc/common-additional-options.markdown) where it states that `trustStorePath` is only applicable with `couchbases://` scheme.

The [docs](https://v2.ottomanjs.com/guides/ottoman.html#authenticating-ottoman-by-certificate) is connecting with `couchbase://` though.

**Comment by deskoh** [comment]
Verified the server cert and client cert authentication working for `alpha.28`.

Is there a way to see the connection logs in couchbase (i.e. connection attempts and which client / IP connected successfully for e.g.).

I also consolidated behaviors of the library when under following condition.

  1. Wrong Client cert/key pair
  ```
  FATAL ERROR:
    libcouchbase experienced an unrecoverable error and terminates the program
    to avoid undefined behavior.
    The program should have generated a "corefile" which may used
    to gather more information about the problem.
    If your system doesn't create "corefiles" I can tell you that the
    assertion failed in C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\ssl\ssl_c.c at line 409
  ```
  2. Mismatched client cert/key or invalid file path specified:
  ```
  this._inst = new binding.Connection(
                 ^

Error: LCB_ERR_SSL_ERROR (1002): A generic error related to the SSL subsystem was encountered. Enable logging to see more details
    at new Connection (D:\code\ottoman-test\node_modules\couchbase\lib\connection.js:129:18)
    at Cluster._getConn (D:\code\ottoman-test\node_modules\couchbase\lib\cluster.js:610:14)
    at new Bucket (D:\code\ottoman-test\node_modules\couchbase\lib\bucket.js:20:26)
    at Cluster.bucket (D:\code\ottoman-test\node_modules\couchbase\lib\cluster.js:482:12)
    at Ottoman.connect (D:\code\ottoman-test\node_modules\ottoman\lib\ottoman\ottoman.js:134:41)
    at Object.<anonymous> (D:\code\ottoman-test\index.js:16:28)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 1002
}
  ```
  3. Mandatory Client Certificate required but none provided:
  ```
  FATAL ERROR:
    libcouchbase experienced an unrecoverable error and terminates the program
...
    assertion failed in C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\ssl\ssl_c.c at line 409
  ```
  4. `trustedStorePath` pointing to a wrong CA
  ```sh
  Error: LCB_ERR_SSL_ERROR (1002): A generic error related to the SSL subsystem was encountered. Enable logging to see more details
...
  code: 1002
  ```

**Comment by AV25242** [comment]
Thats awesome @deskoh  thanks for the testing. 

`Is there a way to see the connection logs in couchbase (i.e. connection attempts and which client / IP connected successfully for e.g.).`

I will see if I can get an answer

**Comment by bwgjoseph** [comment]
Links from bobby https://docs.couchbase.com/server/current/manage/manage-logging/manage-logging.html

**Comment by bwgjoseph** [comment]
@AV25242 have created a separate issue for this and will keep this open for another day before I close this.

Anything else required from us to follow up on the logging portion that you requested?

**Comment by AV25242** [comment]
Thanks @bwgjoseph. Please close this tomorrow
