### ISSUE TITLE
Strange behavior on fresh couchbase setup

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#6]
I notice something weird but not sure what is the issue. Whenever I setup a fresh couchbase using `docker-compose up -d` (can follow the setup in [README](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/README.md)), and after setting up, I set to run only `ottoman-create.test.js` test suite and then I ran `npm test`.

The first time, it throws:

```
$ npm test

> mongoose-vs-ottoman@1.0.0 test Z:\mongoose-vs-ottoman
> mocha test/*.js --exit



  test create function
    1) "before all" hook for "ottoman - should create new doc"


  0 passing (36ms)
  1 failing

  1) test create function
       "before all" hook for "ottoman - should create new doc":
     Uncaught Error: LCB_ERR_UNSUPPORTED_OPERATION (214): Unsupported operation
      at CbConnection.<anonymous> (node_modules\couchbase\lib\connection.js:315:37)
      at AsyncResource.runInAsyncScope (async_hooks.js:186:9)
      at Array.<anonymous> (node_modules\couchbase\lib\connection.js:219:13)
      at Connection._flushPendOps (node_modules\couchbase\lib\connection.js:187:23)
      at Object.<anonymous> (node_modules\couchbase\lib\connection.js:152:14)



npm ERR! Test failed.  See above for more details.
```

The second time I ran `npm test`, it throws

```
$ npm test

> mongoose-vs-ottoman@1.0.0 test Z:\mongoose-vs-ottoman
> mocha test/*.js --exit



  test create function
    1) "before all" hook for "ottoman - should create new doc"


  0 passing (2s)
  1 failing

  1) test create function
       "before all" hook for "ottoman - should create new doc":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (Z:\mongoose-vs-ottoman\test\ottoman-create.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)



npm ERR! Test failed.  See above for more details.
```

Finally, the third time I ran `npm test`, it will pass

```
$ npm test

> mongoose-vs-ottoman@1.0.0 test Z:\mongoose-vs-ottoman
> mocha test/*.js --exit



  test create function
    √ ottoman - should create new doc


  1 passing (297ms)
```

Any subsequent `npm test` looks to be passing too. The logs doesn't seem to have anything as far as I can tell.

I am also able to replicate this issue by re-setup the couchbase (`docker-compose down -v and then docker-compose up -d`). Seem to be consistent behavior

![couchbase-logs-1](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/images/couchbase-logs-1.jpg?raw=true)

**Comment by bwgjoseph** [comment]
@AV25242 replied

We will get back to you on this.

**Comment by bwgjoseph** [comment]
As discussed, this is not critical but I will leave this issue open

**Comment by bwgjoseph** [comment]
After a few round of testing, I don't see this error any more so I will close this issue for now
